apiVersion: apps/v1
kind: Deployment
metadata:
  name: chitti-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chitti
  template:
    metadata:
      labels:
        app: chitti
    spec:
      containers:
        - name: chitti-container
          image: registry.digitalocean.com/ungate/chitti-ungate:development
          ports:
            - containerPort: 3000
            - containerPort: 4000
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60    
            periodSeconds: 60          
            failureThreshold: 10       
            timeoutSeconds: 5         
            successThreshold: 1       
          imagePullPolicy: Always     
          volumeMounts:
            - name: character-config
              mountPath: /app/characters/kaingaroo.character.json
              subPath: defaultChar.json
      imagePullSecrets:
        - name: docker-secret
      volumes:
        - name: character-config
          configMap:
            name: defaultcharacter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
