apiVersion: v1
kind: Service
metadata:
  name: chitti-service
spec:
  selector:
    app: chitti
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 4000
  type: LoadBalancer
